apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    gitlab.com/project-slug: ${{values.repoOwner + "/" + values.repoName}}
    backstage.io/techdocs-ref: url:https://gitlab.com/acme/devops/devhub/backend/devhub
spec:
  type: website
  lifecycle: experimental
  owner: ${{values.owner | dump}}