apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- path: configmaps.yaml
  target:
    kind: ConfigMap
    name: ${{values.component_id}}-config
    version: v1
replacements:
- path: replacement-host.yaml
images:
- name: registry.example/image-example
  {%- if values.imageRepository %}
  newName: ${{ values.imageUrl }}
  {%- endif %}
  newTag: f322fd91    